### ISSUE TITLE
Repack .arc

### ISSUE THREAD

**Issue by Sisulizer** [crskycode/Kaguya_Tool#1]
Can you add create .arc feature too? 
![image](https://user-images.githubusercontent.com/91543117/135748099-6dabecae-51c9-4b37-bd7f-b485db715063.png)

**Comment by crskycode** [comment]
Maybe future.

**Comment by crskycode** [comment]
Thank you, a few days ago, I have finished the reverse engineering of the arc file format. I created a simple repackaging tool, it works, but does not support compression and encryption. I am considering whether I need to implement these features.
