### ISSUE TITLE
Is there any method to get the file message.dat?

### ISSUE THREAD

**Issue by RoadToNowhereX** [crskycode/Kaguya_Tool#10]
How could i unpack the file tblscr.arc to get the file message.dat? The message_tool is not for that, and i could not find a project to do that.

**Comment by crskycode** [comment]
which game?

**Comment by RoadToNowhereX** [comment]
> which game?

In English: [Atelier Kaguya CheshireCat] Nikumesu R30 ~Nikuyoku ni Ochita Mesu-tachi~
In Japanese: [アトリエかぐや CheshireCat] 肉牝R30 ～肉欲に堕ちた牝たち～

According to the forum 澄空学院 and the project FuckGalEngine/竹子 on github, the process of unpacking the tblscr.arc seem to be connected with tblscr.ari and scr.arc.

**Comment by Cosetto** [comment]
Use [this tool](https://github.com/satan53x/SExtractor)  for tblscr.arc
Crsky's tool is for a different version of Kaguya engine

**Comment by RoadToNowhereX** [comment]
> Use [this tool](https://github.com/satan53x/SExtractor) for tblscr.arc Crsky's tool is for a different version of Kaguya engine

Thanks a lot!
