### ISSUE TITLE
Questions about updated Kaguya engine

### ISSUE THREAD

**Issue by SkylightStudio07** [crskycode/Kaguya_Tool#11]
Thank you for your hard work always.

Kaguya engine games released from 2023 have confirmed that they do not use message.dat and param.dat.

May I know where these new forms of Kaguya engine games store script files?

I think it's integrated into tblstr.arc, but maybe it's integrated into the exe file like some Kirikiri Engine games.

The game that i test is Shibora Renkare Keiyaku Hataraku Otona no Onee-san to H na Rental Kareshi Seikatsu(2024, Atelier Kaguya CheshireCat)

**Comment by Cosetto** [comment]
Message.dat and Param.dat are different version of Kaguya engine, they're from [Bare & Bunny](https://vndb.org/p3903) and [HonkyTonk Pumpkin](https://vndb.org/p986).

**Comment by SkylightStudio07** [comment]
https://github.com/satan53x/SExtractor

I found a good tool while browsing your issue. Thank you for your help!
