### ISSUE TITLE
Any chance of supporting [SCR-Ver5.3]?

### ISSUE THREAD

**Issue by YukinoAi** [crskycode/Kaguya_Tool#12]
User error. Nevermind.

**Comment by Cosetto** [comment]
>[Mama x Holic](https://vndb.org/v28731) released in 2020 uses message.dat files that have the header [SCR-MESSAGE]ver4.0 and >is labled as using the "KaGuYa" game engine.
>I was able to use this tool to extract strings successfully using MsgTool.exe.

You just literally said it. Strtool is for tblstr.arc from another KaGuya version

**Comment by YukinoAi** [comment]
You responded too fast~
