### ISSUE TITLE
About the font

### ISSUE THREAD

**Issue by MinscyBubu** [crskycode/Kaguya_Tool#2]
Hello, thanks for create this tools, i was wondering if there's a chance to make something to modified the font, I want to make a french translation but i need use special characters for that, thanks in advance!

**Comment by crskycode** [comment]
change font will be need to hack the engine

> > Hello, thanks for create this tools, i was wondering if there's a chance to make something to modified the font, I want to make a french translation but i need use special characters for that, thanks in advance!
> 
> Tool supports only shift_jis and gbk so you can only use english

[Double-byte Character Sets](https://docs.microsoft.com/en-us/windows/win32/intl/double-byte-character-sets) can be used on Kaguya engine. Using non-shift_jis will need to hacking the engine.

**Comment by crskycode** [comment]
> > About the custom fonts, there is always need to hacking the engine.
> 
> Crsky if you don't mind, will you create a repacker for nekosdk (.pak) https://vndb.org/v27685. Scripts is in plain text so it's easy and it can read from directory. I'm trying to compress the game so I need a repacker for it.

[NEW TOOL](https://github.com/crskycode/NekoGameSDK_PackTool) Done

**Comment by Cosetto** [comment]
> > > About the custom fonts, there is always need to hacking the engine.
> > 
> > 
> > Crsky if you don't mind, will you create a repacker for nekosdk (.pak) https://vndb.org/v27685. Scripts is in plain text so it's easy and it can read from directory. I'm trying to compress the game so I need a repacker for it.
> 
> [NEW TOOL](https://github.com/crskycode/NekoGameSDK_PackTool) Done

Thank you.
