### ISSUE TITLE
how to used

### ISSUE THREAD

**Issue by RRB21** [crskycode/Kaguya_Tool#3]
I can't start the exe after I press a key and the program close

**Comment by Cosetto** [comment]
> I can't start the exe after I press a key and the program close
You have to start it with cmd

**Comment by RRB21** [comment]
Hmm okay but I still don't get it how I can extract the files

**Comment by xenei** [comment]
> Hmm okay but I still don't get it how I can extract the files

Looks like you're pretty new to this, it'd be hard to explain everything to you here so kindly contact me at Discord my user tag is - xe#0422

And Also Can you now please close this issue ?

**Comment by Cosetto** [comment]
> Hmm okay but I still don't get it how I can extract the files

Just type the exe name and it will show you the command

**Comment by RRB21** [comment]
> - xe#422

Thank you and I will close the issue but can you tell me ur username again I can't find you on discord

**Comment by Cosetto** [comment]
> > * xe#422
> 
> Thank you and I will close the issue but can you tell me ur username again I can't find you on discord. I think you miss the last number - xe#422.....

here's the server https://discord.gg/x4RXg8ef
