### ISSUE TITLE
Kaguya Pic Merge

### ISSUE THREAD

**Issue by 28598519a** [crskycode/Kaguya_Tool#4]
For cg*.arc、sp*.arc、vrm.arc

after extract those pack, the *.alp file or the image in *.anm、*.plt, check every image Offset 04、08 can get the X Y coordinate.
([GetKaguyaXY.py](https://github.com/28598519a/GetKaguyaXY/blob/main/GetKaguyaXY.py)) or If use [exl6ren](http://asmodean.reverse.net/pages/exl6ren.html) you will get file name like that "cg000A顔1+x56y0".

But what is the merge rule? It seems the merge table is in pararms.dat, Can you help to add a tool to decode/export the merge table in pararms.dat? 
The merge process will look like that, if we don't get the table, it will looks disorder
example1: cg000 + cg000A顔1 + cg000Bモ1甲 = Result1
example2: cg000_1 + cg000A顔1 + cg000Bモ2甲 = Result2
example3: cg000 + cg000A顔1 + cg000Bモ3甲 = Result3
example4: Result2 + cg000A顔3 + cg000Cモ2甲 = Result4

**Comment by crskycode** [comment]
Want to get the CG definition ?

**Comment by 28598519a** [comment]
我原本是直接用猜測法去合成CG的https://github.com/28598519a/KaguyaMerge，但是我發現猜測法終究有極限
Kaguya的CG或是SP，他引擎應該有一個合成表，才能知道需要哪些圖片組成一個畫面顯示在遊戲中 (如同我上面提的Example，需要多圖和出顯示畫面，但是一張CG或著SP等，需要由哪些圖來構成這需要得到他引擎的合成表，而我認為應該在Pararms.dat中)

**Comment by 28598519a** [comment]
For Kaguya CG or SP, the engine should have a merge table to know which pictures are needed to make up a final screen image in the game. 
As the Example I mentioned above, it is necessary to combine multiple pictures to create a display picture, but what pictures should be composed of a CG or SP?
This requires the merge table in engine, which I think should be defined in pararms.dat.

**Comment by 28598519a** [comment]
> Want to get the CG definition ?

目的是希望拿到CG、SP定義表來做CG、SP合成，因為一個CG的組成是由許多元件所組成，我需要這個組成的定義表，而這應該被定義在pararms.dat中，但我對於解析pararms.dat中的資訊無能為力，希望你能協助

**Comment by crskycode** [comment]
我把以前写的解析`params.dat`的代码放到仓库中了，这是个半成品程序，它可以正确读取`params.dat`的数据，我已经还原了一部分数据的名字，但更具体的数据，你需要将这个程序跑起来，自行分析。

**Comment by 28598519a** [comment]
> 我把以前写的解析`params.dat`的代码放到仓库中了，这是个半成品程序，它可以正确读取`params.dat`的数据，我已经还原了一部分数据的名字，但更具体的数据，你需要将这个程序跑起来，自行分析。

一运行就挂了...您可以直接帮忙解析出CG段吗? 這是樣本[params.zip](https://github.com/crskycode/Kaguya_Tool/files/7979809/params.zip)

![image](https://user-images.githubusercontent.com/33422418/152001955-b3507cdd-76ba-4a52-90bb-2bdf10125c6c.png)

**Comment by crskycode** [comment]
不能。对于不同版本的`Kaguya`引擎，其使用的`params.dat`文件结构也有所不同，需要分析引擎来确认这些结构，但我并没有太多时间来帮你分析你想提取的游戏。你截图中的错误是由于程序解析到了一个未知的参数，该参数只有分析具体的游戏引擎才可以确定如何进行读取。

**Comment by 28598519a** [comment]
> 不能。对于不同版本的`Kaguya`引擎，其使用的`params.dat`文件结构也有所不同，需要分析引擎来确认这些结构，但我并没有太多时间来帮你分析你想提取的游戏。你截图中的错误是由于程序解析到了一个未知的参数，该参数只有分析具体的游戏引擎才可以确定如何进行读取。如果你想知道如何分析该文件，我可以分享一些经验。

我需要知道怎么分析，但在这之前我想先问一下，我试了另一个params.dat (我Kaguya的游戏积了很多要拆，但全都卡在CG合成)，运行后直接结束是?

**Comment by 28598519a** [comment]
关于CG有什么推荐下手的点吗，因为我对params.dat的结构完全没概念，我不知道要在什么地方下断点合适以及下了之后我感兴趣的值应该要是什么...

**Comment by crskycode** [comment]
> 关于CG有什么推荐下手的点吗，因为我对params.dat的结构完全没概念，我不知道要在什么地方下断点合适以及下了之后我感兴趣的值应该要是什么...
> 
> 程序里也没有注解...只单纯呆看代码老实说无法理解你的思路

那你就从`Load`函数开始一步步跟吧，这个文件的结构就是这样的。

**Comment by 28598519a** [comment]
我在_cg.Deserialize这边断点，里面的Key是CG名称，cg确实是00~79没错
![image](https://user-images.githubusercontent.com/33422418/152012178-6abb1f45-7924-48cb-83a5-2318e0c8332f.png)

我举一组key=cg_078 count=51, value=1923~1973，实际拆出来的cg_078有底图有2张 (cg_078、cg_078_1)，含各个差分元件共182张，value只是一堆int32值好像没什用?

你前面指的分析是指这些value怎么变String吗?

**Comment by 28598519a** [comment]
为什么我 var p = string.Format("{0:X}", reader.BaseStream.Position);
显示出来的Offset跟实际的好像不太一样?

**Comment by 28598519a** [comment]
> 如果程序可以正常执行完，那么`params.dat`文件的全部数据就应该已经读取完成了，你仔细看看这些数据，结合cg文件名和序号来猜吧。上面提到的“XOR表”是程序里的`_bmpKey`，用于解密cg图像的。

_cg 文字的部分只有key的cg_xx而已，关于value的那些int值你有什么想说明的吗? 其余的颜、Bモ、部什么的元件都没出现，这样要怎么猜?
_item是有這些文字，但內容也只是指向是存在哪個.arc裡

**Comment by crskycode** [comment]
我观察了一下，`_pattern._cg._collection[]._values`里的数值应该是`_pattern._items._collection`这个集合的索引，这就是引用关系。

**Comment by crskycode** [comment]
我更新了一点代码，现在可以导出CG定义信息了。

**Comment by 28598519a** [comment]
看起来把每个diff里的index合起来就是CG
谢谢 👍 

然后你目前的输出会是一堆unicode \uxxx什么的，建议你的Code要稍微修改一点，如下
```
using System.Text.Encodings.Web;
using System.Text.Unicode;

var options = new JsonSerializerOptions { Encoder = JavaScriptEncoder.Create(UnicodeRanges.All), WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
```

**Comment by crskycode** [comment]
> 看起来把每个diff里的index合起来就是CG 谢谢 👍
> 
> 然后你目前的输出会是一堆unicode \uxxx什么的，建议你的Code要稍微修改一点，如下
> 
> ```
> using System.Text.Encodings.Web;
> using System.Text.Unicode;
> 
> var options = new JsonSerializerOptions { Encoder = JavaScriptEncoder.Create(UnicodeRanges.All), WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
> ```

不需要这样修改，JsonSerializer会自动还原那些被转义的字。

**Comment by 28598519a** [comment]
> 不需要这样修改，JsonSerializer会自动还原那些被转义的字。

不修改
![image](https://user-images.githubusercontent.com/33422418/152317445-f4a39745-11e4-4a71-8bc1-ec4286852b0c.png)

修改
![image](https://user-images.githubusercontent.com/33422418/152317487-d6c97bed-e791-4e09-8285-3e91a8aac575.png)

**Comment by crskycode** [comment]
> > 不需要这样修改，JsonSerializer会自动还原那些被转义的字。
> 
> 不修改 ![image](https://user-images.githubusercontent.com/33422418/152317445-f4a39745-11e4-4a71-8bc1-ec4286852b0c.png)
> 
> 修改 ![image](https://user-images.githubusercontent.com/33422418/152317487-d6c97bed-e791-4e09-8285-3e91a8aac575.png)

只要程序能读就行了，又不用人工处理。这种事情交给程序自动化处理。
