### ISSUE TITLE
the game LOVEトレ ～エッチな恋愛トレーニング～，after import the text, some text will appear garbled

### ISSUE THREAD

**Issue by yqw1231** [crskycode/Kaguya_Tool#7]

**Comment by crskycode** [comment]
Do not use any unsupported character.

**Comment by yqw1231** [comment]
> Do not use any unsupported character.

就是一句简单的中文，并没有其他单词

**Comment by crskycode** [comment]
Try rebuild script with `shift_jis` encoding and don't change any text.

**Comment by yqw1231** [comment]
> Try rebuild script with `shift_jis` encoding and don't change any text. This tests the tool is working correctly
我尝试将message.new.dat使用`shift_jis`重新编码，但是发现还是会出现少部分文字乱码的情况，请问是我理解错大佬你的意思了吗？

**Comment by yqw1231** [comment]
经过测试，将澪火这个名字修改成别的，就不存在文本乱码了，应该是澪这个字超出编码范围了
