### ISSUE TITLE
the game "JD温泉。 エロエロダイナマイト女子大生との温泉生活。"

### ISSUE THREAD

**Issue by yqw1231** [crskycode/Kaguya_Tool#8]
When the article reach C0000038B, the program freezes and exits, generating the file MES526B.tmp

**Comment by Cosetto** [comment]
I'm not sure what do you mean by that? Please provide more info

**Comment by yqw1231** [comment]
When the next sentence is displayed, "Program is not responding."
[MES526B.zip](https://github.com/crskycode/Kaguya_Tool/files/11982724/MES526B.zip)

**Comment by yqw1231** [comment]
vntextpatch cannot implement a packet

**Comment by Cosetto** [comment]
I still don't understand what do you mean. Like there's something wrong with the tool when dealing with message.dat, and it breaks the game? Or something wrong with packer, which is used to repack .arc archive?

**Comment by yqw1231** [comment]
I used the message.dat generated by your tool to replace the original message.dat of the game. Then when the sentence C0000038B is run, the game process must crash.

**Comment by Cosetto** [comment]
Test with this sentence, "The quick brown fox jumps over the lazy dog."
Try if the game crash or not

**Comment by yqw1231** [comment]
Use english?

**Comment by yqw1231** [comment]
![QQ截图20230707222854](https://github.com/crskycode/Kaguya_Tool/assets/136776881/e66556bf-be86-4d1a-bdad-e2d713d67ba9)
like this?

**Comment by Cosetto** [comment]
Yes. And the command to insert: msgtool.exe -b shift-jis shift-jis message.dat

**Comment by yqw1231** [comment]
Not crash.

**Comment by yqw1231** [comment]
It's the first time this has happened to me.

**Comment by yqw1231** [comment]
After a series of explorations and explorations, I found the factors that would cause the jam. But it was recently discovered that the symbol "♪", when converted to gbk coding, becomes "?" Is there any good solution? Can you give some guidance and suggestions? Thank you very much.

**Comment by TXT2GAM** [comment]
♡ ♪ ・这几种符号在gbk编码里都没有，建议封包前替换或直接删除

**Comment by Yczcode** [comment]
./MsgTool -e shift_jis message.dat导出message.txt后更  change message.dat 后
封装 ./MsgTool -b shift_jis gbk message.dat 后乱码。原文件解包出来直接封装回去也是乱码
