### ISSUE TITLE
params_tool

### ISSUE THREAD

**Issue by Weitsaii** [crskycode/Kaguya_Tool#9]
Hello,how do I use params_tool? What is the command?,thank you!

**Comment by Weitsaii** [comment]
Have fumbled out, solved the problem, thank you for writing tools!

**Comment by Weitsaii** [comment]
Now found a problem, when the proposed JSON text import, there will be some characters displayed? Like Mom.

**Comment by Weitsaii** [comment]
After testing, the params.dat file version v05.6 cannot be extracted

**Comment by Weitsaii** [comment]
> MaMa x holic. I tested it. The word 妈 says "?" in the title. Mark character

**Comment by Cosetto** [comment]
> > MaMa x holic. I tested it. The word 妈 says "?" in the title. Mark character

You need to change the encoding to GBK, original encoding is Shift-jis

**Comment by Weitsaii** [comment]
> > > 妈妈 x 狂热。我测试过。妈这个字说的是“？” 在标题中。标记字符
> 
> 需要将编码改为GBK，原来的编码是Shift-jis
Is the encoding of the extracted JSON text？

**Comment by Weitsaii** [comment]
> > > > 妈妈x狂热。我测试过。妈这个字说的是“？”在标题中。标记字符
> > 
> > 
> > 需要将编码改为GBK，原来的编码是Shift-jis
> > 是提取的JSON文本的编码吗？

extract
Params_Tool_export.exe -e shift_jis params.dat

backseal
Params_Tool_import.exe -b shift_jis gbk  params.dat
This is the corresponding command

**Comment by Cosetto** [comment]
Oh wait, I think the params_tool encodes back Shift-jis not GBK. I think you should ask Crsky about this

**Comment by Weitsaii** [comment]
> 
I'm sorry. I don't know this guy

**Comment by Cosetto** [comment]
> > > > > 妈妈x狂热。我测试过。妈这个字说的是“？”在标题中。标记字符
> > > 
> > > 
> > > 需要将编码改为GBK，原来的编码是Shift-jis
> > > 是提取的JSON文本的编码吗？
> 
> extract Params_Tool_export.exe -e shift_jis params.dat
> 
> backseal Params_Tool_import.exe -b shift_jis gbk params.dat This is the corresponding command

Nope, I made it to be click action only, it doesn't have any command
Like Load(@.\params.dat), Export(@.\params.json)

**Comment by Cosetto** [comment]
Or you can seek help from [Dir-A](https://github.com/Dir-A?tab=repositories), he may know how to deal with GBK encode

**Comment by Weitsaii** [comment]
> > > > > > 妈妈x狂热。是我测试过。妈这个字说“？”在标题中。标记字符
> > > > 
> > > > 
> > > > 需要将编码改为GBK，原来的编码是Shift-jis
> > > > 是提取的JSON文本的编码吗？
> > 
> > 
> > 提取 Params_Tool_export.exe -e shift_jis params.dat
> > backseal Params_Tool_import.exe -b shift_jis gbk params.dat 这是对应的命令
> 
> 不，我只是将其设置为单击操作，它没有任何命令， 例如 Load(@.\params.dat)、Export(@.\params.json)



> [或者你可以向Dir-A](https://github.com/Dir-A?tab=repositories)寻求帮助，他可能知道如何处理 GBK 编码

I can't do that either. I don't know why, but the title appears to be read in utf-16 encoding

**Comment by Weitsaii** [comment]
> 

Dir-A，I asked a question once, and when I didn't answer, I didn't dare ask it again

**Comment by Cosetto** [comment]
> 

Oh, might be because the encode of exe is shift-jis? The best method right now is hook if I guess. Dir-A maybe busy, he just talked with me days ago. Also, I got this from pan.baidu, I'm not sure what it does
[竹子社中文显示库.zip](https://github.com/crskycode/Kaguya_Tool/files/12260489/default.zip)

**Comment by Weitsaii** [comment]
> > 
> 
> 哦，可能是因为exe的编码是shift-jis？如果我猜的话，现在最好的方法是 hook。Dir-A 可能很忙，他几天前才和我聊过。另外，我从pan.baidu得到这个，我不知道它是做什么的，看起来他们把字体改成了Simhei和GBK编码 [竹子社中文显示库.zip](https://github.com/crskycode/Kaguya_Tool/files/12260489/default.zip)

This is the Bamboo Club's Chinese language package
HOOK method. Do you have the project address? I'm a white boy

**Comment by Cosetto** [comment]
I don't know. I just came across it while messing with a tool called Tiny翻译肋手

**Comment by Weitsaii** [comment]
> 我不知道。我刚刚在摆弄一个名为“TinyTranslfO”的工具时发现了它
This is still a little different from the extraction script of this project, the text will not change according to the length of the translation, that is, truncated, so this is not good.
